


spring:
  datasource:
    url: jdbc:mysql://cdb-phybktho.cd.tencentcdb.com:10054/db_album?characterEncoding=utf-8
    password: 
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-actove: 20
